### ISSUE TITLE
Found could be Any_of

### ISSUE THREAD

**Issue by Sebanisu** [codereport/An-Algorithm-Library#5]
https://github.com/codereport/An-Algorithm-Library/blob/50b4cb9889161aa6c68e7e426f8d4009baf5fd6b/src/aal/algorithm.hpp#L19
https://youtu.be/qxHI2ckjcZU?t=3351 responding to your latest stream.
Referring to aal::var::found could be aal::var::any_of. As std::any_of takes a predicate and returns true if any are true. Also std::all_of and std::none_of. 
https://en.cppreference.com/w/cpp/algorithm/all_any_none_of

**Comment by codereport** [comment]
You are definitely correct. That is subtely hinted at in my [STL Cheat Sheet](https://github.com/codereport/Algorithms/blob/master/CheatSheet/The%20STL%20Algorithm%20Cheat%20Sheet%20v0.0.pdf) but I think I should make it explicit. Will update in the next livestream.

**Comment by codereport** [comment]
Wrote a blog about it! Thanks for inspiring me https://codereport.github.io/Algorithm-Selection/
